#!/usr/bin/env python3
"""
codegen.py -- audioguidegui Phase 2 (delivered as codegen_v1.py)
Generates a native audioguide options file (.py) from a project dict.
The generated file is also directly usable with the stock CLI:
    python3 agConcatenate.py generatedfile.py

## INTERPRETIVE: emission order is flat options first (sorted), then TARGET,
## CORPUS, SEARCH, SUPERIMPOSE, INSTRUMENTS. Options files are declarative,
## so ordering does not affect behavior; sorting makes diffs stable.
"""


def py_literal(v):
    """JSON-safe project value -> python source text."""
    if isinstance(v, dict) and '__tuple__' in v:
        items = [py_literal(x) for x in v['__tuple__']]
        return '(%s,)' % items[0] if len(items) == 1 else '(%s)' % ', '.join(items)
    if isinstance(v, dict) and '__dict__' in v:
        return '{%s}' % ', '.join('%s: %s' % (py_literal(k), py_literal(x))
                                  for k, x in v['__dict__'])
    if isinstance(v, dict) and '__obj__' in v:
        parts = [py_literal(a) for a in v.get('args', [])]
        parts += ['%s=%s' % (k, py_literal(x))
                  for k, x in v.get('kwargs', {}).items()]
        return '%s(%s)' % (v['__obj__'], ', '.join(parts))
    if isinstance(v, dict):
        return '{%s}' % ', '.join('%s: %s' % (py_literal(k), py_literal(x))
                                  for k, x in v.items())
    if isinstance(v, list):
        return '[%s]' % ', '.join(py_literal(x) for x in v)
    if isinstance(v, bool):
        return 'True' if v else 'False'
    if v is None:
        return 'None'
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return repr(v)
    raise TypeError('cannot render value: %r' % (v,))


def _call(objname, node):
    parts = [py_literal(a) for a in node.get('args', [])]
    parts += ['%s=%s' % (k, py_literal(v))
              for k, v in node.get('kwargs', {}).items()]
    return '%s(%s)' % (objname, ', '.join(parts))


def generate(prj):
    """Project dict -> options file text."""
    out = []
    out.append('# generated by audioguidegui from project %r' % prj.get('name', ''))
    out.append('')
    for name in sorted(prj.get('options', {})):
        out.append('%s = %s' % (name, py_literal(prj['options'][name])))
    if prj.get('options'):
        out.append('')
    if prj.get('target') is not None:
        out.append('TARGET = ' + _call('tsf', prj['target']))
        out.append('')
    if prj.get('corpus'):
        out.append('CORPUS = [')
        for node in prj['corpus']:
            out.append('\t' + _call('csf', node) + ',')
        out.append(']')
        out.append('')
    if prj.get('search'):
        out.append('SEARCH = [')
        for node in prj['search']:
            out.append('\t' + _call('spass', node) + ',')
        out.append(']')
        out.append('')
    if prj.get('superimpose') is not None:
        out.append('SUPERIMPOSE = ' + _call('si', prj['superimpose']))
        out.append('')
    if prj.get('instruments_raw', '').strip():
        out.append(prj['instruments_raw'].strip())
        out.append('')
    return '\n'.join(out)


def write(prj, path):
    with open(path, 'w', encoding='utf-8') as fh:
        fh.write(generate(prj))
    return path
